version: "3.1"
services:
  postgres: # postgresql
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d
    networks:
      - api-network
      - gui-network

  pgadmin: # pgadmin4
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - gui-network
  
  go-api: # go-api
    container_name: go-api
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    depends_on:
      - postgres
    networks:
      - api-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  api-network:
    name: api-network
  gui-network:
    name: gui-network
