version: "3.1"
services:
  go-api:
    container_name: go-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - go-app:/app
    ports:
      - "6000:6000"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/health"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - api-network
      - communication-network

  postgres: # postgresql
    image: postgres:13
    environment:
      POSTGRES_USER: admindb
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d
    networks:
      - database-network
      - communication-network

  pgadmin: # pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - database-network
      - communication-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
  go-app:

networks:
  database-network:
    driver: bridge
  api-network:
    driver: bridge
  communication-network:
    driver: bridge
